version: '3.7'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    networks:
      - my-network

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - my-network

volumes:
  influxdb_data:
  grafana_data:

networks:
  my-network:
    driver: bridge
